### PR TITLE
Added Material Design And More...

### PR DESCRIPTION
**Pull request by Richienb**
- Added Material Design to make it look more stylish.
- Changed the comment dialogue box to also feature MD.
- Added a simple application icon
- Automatically adds an API key if one isn't already entered
- Added a splash screen
- Renamed `Link` to `URL` which is a more formal and better-sounding name
- Changed the URL colour palette to more match material design
- Added a `browse`, `next` and `previous` icon
- Updated Restsharp to the latest compatible version which still works (104.5.0)
- For this to work, the target framework has been moved up to 4.0 but this will not affect any devices as all devices running .net 3.5 are already compatible with .net 4.0

### CODE REVIEW

**Comment by omegatechware** [comment]
@Richienb : Would you like to fork this instead? Although the UI definitely could use some sprucing up, my intent was to create a Q&D example with as few dependencies/requirements as possible. Also, I have a few questions about your code. Could you contact me privately to discuss it (If that's even possible - I don't know my way around Git as well as I probably should)? Thanks!

**Comment by Richienb** [comment]
How would I contact you? Do you have an email I can use? Or how else should I do so?

**Comment by omegatechware** [comment]
I'm sending you an email shortly. :)

**Comment by Richienb** [comment]
I've just made a few more minor changes that you outlined in the email as another pull

**Pull request merged**
